source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
target 'youyu' do
    pod 'IMYWebView'
    pod 'WebViewJavascriptBridge', '~> 6.0'
    pod 'QMUIKit'
    pod 'ReactiveObjC'
    pod 'YTKNetwork'
    pod 'YTKKeyValueStore'
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'MBProgressHUD'
    pod 'EAIntroView'
    pod 'TPKeyboardAvoiding'
    pod 'DZNEmptyDataSet', '~>  1.7.3'
    pod 'SDCycleScrollView','~> 1.75'
    pod 'SWTableViewCell'
    pod 'SDWebImage'
    pod 'UITableView+FDTemplateLayoutCell'
    pod 'Masonry'
    pod 'YYModel'
    pod 'XHLaunchAd'
    pod 'BlocksKit'
    pod 'LLPay'
    pod 'Hyphenate'
    
    pod 'UMCCommon'
    pod 'UMCSecurityPlugins'
    pod 'UMCAnalytics'
    pod 'UMCPush'
    pod 'UMengUShare/UI'
    pod 'UMengUShare/Social/ReducedWeChat'
    pod 'UMengUShare/Social/ReducedQQ'
    pod 'UMengUShare/Social/ReducedSina'

end
